import {
  BookOpenIcon,
  BookmarkSquareIcon,
  CodeBracketIcon,
  CommandLineIcon,
  DocumentTextIcon,
  PuzzlePieceIcon,
  DocumentIcon,
  CodeBracketSquareIcon,
  AcademicCapIcon,
  BeakerIcon,
  LightBulbIcon,
  WrenchIcon,
  WrenchScrewdriverIcon,
  ServerIcon,
  CubeIcon,
  CpuChipIcon,
  LifebuoyIcon,
  QuestionMarkCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  ChatBubbleBottomCenterTextIcon,
  CheckCircleIcon,
  ArrowPathIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  RocketLaunchIcon,
  LinkIcon,
  ShieldCheckIcon,
  CogIcon,
  Cog6ToothIcon,
  ChartBarIcon,
  ChartPieIcon,
  WindowIcon,
  TableCellsIcon
} from '@heroicons/react/24/outline';

// İkon adlarını JSX elementlerine dönüştüren bir harita
export const iconMap: Record<string, React.ComponentType<React.ComponentProps<'svg'>>> = {
  BookOpen: BookOpenIcon,
  Download: BookOpenIcon,
  BookmarkSquare: BookmarkSquareIcon,
  CodeBracket: CodeBracketIcon,
  CommandLine: CommandLineIcon,
  DocumentText: DocumentTextIcon,
  Puzzle: PuzzlePieceIcon,
  Document: DocumentIcon,
  Code: CodeBracketSquareIcon,
  AcademicCap: AcademicCapIcon,
  Beaker: BeakerIcon,
  LightBulb: LightBulbIcon,
  Wrench: WrenchIcon,
  WrenchScrewdriver: WrenchScrewdriverIcon,
  Server: ServerIcon,
  Cube: CubeIcon,
  CpuChip: CpuChipIcon,
  Lifebuoy: LifebuoyIcon,
  QuestionMarkCircle: QuestionMarkCircleIcon,
  ExclamationTriangle: ExclamationTriangleIcon,
  InformationCircle: InformationCircleIcon,
  ChatBubble: ChatBubbleBottomCenterTextIcon,
  CheckCircle: CheckCircleIcon,
  ArrowPath: ArrowPathIcon,
  ClipboardDocument: ClipboardDocumentIcon,
  ClipboardList: ClipboardDocumentListIcon,
  RocketLaunch: RocketLaunchIcon,
  Link: LinkIcon,
  ShieldCheck: ShieldCheckIcon,
  Cog: CogIcon,
  Cog6Tooth: Cog6ToothIcon,
  ChartBar: ChartBarIcon,
  ChartPie: ChartPieIcon,
  Window: WindowIcon,
  TableCells: TableCellsIcon
}; 