name: Next.js CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install pnpm
        run: npm i -g pnpm
          
      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpx prisma generate

      - name: Sleep
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Build Next.js
        run: pnpm run build